name = "AeroSMP Season 2"
author = "Create-O-Holics"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1ecd20b83faab0be5d543acbe4664ee96d6633ee2fcac978668156e5a83020f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
